### ISSUE TITLE
Can you please add the following WACV 2021 paper in repo 

### ISSUE THREAD

**Issue by vinodkkurmi** [prprbr/awesome-lifelong-continual-learning#1]
Hi @prprbr   please add the following  WACV 2021 paper in repo.
Paper: https://openaccess.thecvf.com/content/WACV2021/html/Kurmi_Do_Not_Forget_to_Attend_to_Uncertainty_While_Mitigating_Catastrophic_WACV_2021_paper.html
Project: https://delta-lab-iitk.github.io/Incremental-learning-AU/
Thanks

**Comment by prprbr** [comment]
Added.

If you want to add further paper(s), please do a pull request. Thanks
